site: Ezra Iksu Eom
title: Ezra Iksu Eom
description: >-
  Just do it what you want.
googlewebfonts: Fira+Code:wght@400;500;700
lang: ko-KR
timezone: Seoul
repo: https://github.com/ywen407/ywen407.github.io # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: Ezra
  bio: Just do it what you want.
  username: Ezra # general username
  github: Ezra Iksu Eom # github username
  twitter: none # twitter username
  email: ywen407@naver.com # email adress

# URL settings
url: "https://ywen407.github.io" #
baseurl: "" # leave blank if not wishd
permalink: "https://ywen407.github.io"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


